package com.otv.model.mod;

// Generated 29 août 2014 22:56:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Eligibilite generated by hbm2java
 */
@Entity
@Table(name = "eligibilite", catalog = "ref")
public class Eligibilite implements java.io.Serializable {

	private String identifiant;
	private String creditEncours;
	private String impaye;
	private String salarie;

	public Eligibilite() {
	}

	public Eligibilite(String identifiant) {
		this.identifiant = identifiant;
	}

	public Eligibilite(String identifiant, String creditEncours, String impaye,
			String salarie) {
		this.identifiant = identifiant;
		this.creditEncours = creditEncours;
		this.impaye = impaye;
		this.salarie = salarie;
	}

	@Id
	@Column(name = "identifiant", unique = true, nullable = false, length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "creditEncours", length = 50)
	public String getCreditEncours() {
		return this.creditEncours;
	}

	public void setCreditEncours(String creditEncours) {
		this.creditEncours = creditEncours;
	}

	@Column(name = "impaye", length = 50)
	public String getImpaye() {
		return this.impaye;
	}

	public void setImpaye(String impaye) {
		this.impaye = impaye;
	}

	@Column(name = "salarie", length = 50)
	public String getSalarie() {
		return this.salarie;
	}

	public void setSalarie(String salarie) {
		this.salarie = salarie;
	}

}
