package com.otv.model.mod;

// Generated 24 juin 2014 18:08:05 by Hibernate Tools 3.4.0.CR1

import java.awt.Color;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Revenuordepense generated by hbm2java
 */
@Entity
@Table(name = "revenuordepense", catalog = "ref")
public class Revenuordepense implements java.io.Serializable {

	private String libelle;
	private Long montant;
	private String type;
	private Date date;
	@Transient
	private String image;
	@Transient
	private String color;

	public Revenuordepense() {
	}

	public Revenuordepense(String libelle) {
		this.libelle = libelle;
	}

	public Revenuordepense(String libelle, Long montant, String type, Date date) {
		this.libelle = libelle;
		this.montant = montant;
		this.type = type;
		this.date = date;
	}

	@Id
	@Column(name = "libelle", unique = true, nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "montant", precision = 10, scale = 0)
	public Long getMontant() {
		return this.montant;
	}

	public void setMontant(Long montant) {
		this.montant = montant;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Transient
	public String getImage() {
		if(this.getType().startsWith("DEP"))
		{
			return "img/moins.png";
		}
		else
		return "img/plus.png";
	}

	@Transient
	public void setImage(String image) {
		this.image = image;
	}

	@Transient
	public String getColor() {
		return "Color.yellow";
	}
	
	@Transient
	public void setColor(String color) {
		this.color = color;
	}
	
}
