package com.otv.model.mod;

// Generated 2 sept. 2014 21:45:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Scoreparametrage generated by hbm2java
 */
@Entity
@Table(name = "scoreparametrage", catalog = "ref")
public class Scoreparametrage implements java.io.Serializable {

	private String identifiant;
	private Integer scoreHomme;
	private Integer scoreFemme;
	private Integer scoreOuvrier;
	private Integer scoreCadre;
	private Integer scoreFonctionPublique;
	private Integer scoreSecteurPrive;
	private Integer scoreCelibataire;
	private Integer scoreMarie;
	private Integer scoreLocataire;
	private Integer scorePropriétaire;
	private Integer revenuSup;
	private Integer revenuInf;
	private Integer nombreEnfantInf;
	private Integer nombreEnfantSup;
	private Integer ageInf;
	private Integer ageSup;
	private Boolean actifBooleanHomme;
	private Boolean actifBooleanFemme;
	private Boolean actifBooleanOuvrier;
	private Boolean actifBooleanCadre;
	private Boolean actifBooleanSecteurPrive;
	private Boolean actifBooleanCelibataire;
	private Boolean actifBooleanMarie;
	private Boolean actifBooleanLocataire;
	private Boolean actifBooleanPropriétaire;
	private Boolean actifBooleanRevenuSup;
	private Boolean actifBooleanRevenuInf;
	private Boolean actifBooleanEnfantInf;
	private Boolean actifBooleanEnfantSup;
	private Boolean actifBooleanAgeInf;
	private Boolean actifBooleanAgeSup;

	public Scoreparametrage() {
	}

	public Scoreparametrage(String identifiant) {
		this.identifiant = identifiant;
	}

	public Scoreparametrage(String identifiant, Integer scoreHomme,
			Integer scoreFemme, Integer scoreOuvrier, Integer scoreCadre,
			Integer scoreFonctionPublique, Integer scoreSecteurPrive,
			Integer scoreCelibataire, Integer scoreMarie,
			Integer scoreLocataire, Integer scorePropriétaire,
			Integer revenuSup, Integer revenuInf, Integer nombreEnfantInf,
			Integer nombreEnfantSup, Integer ageInf, Integer ageSup,
			Boolean actifBooleanHomme, Boolean actifBooleanFemme,
			Boolean actifBooleanOuvrier, Boolean actifBooleanCadre,
			Boolean actifBooleanSecteurPrive, Boolean actifBooleanCelibataire,
			Boolean actifBooleanMarie, Boolean actifBooleanLocataire,
			Boolean actifBooleanPropriétaire, Boolean actifBooleanRevenuSup,
			Boolean actifBooleanRevenuInf, Boolean actifBooleanEnfantInf,
			Boolean actifBooleanEnfantSup, Boolean actifBooleanAgeInf,
			Boolean actifBooleanAgeSup) {
		this.identifiant = identifiant;
		this.scoreHomme = scoreHomme;
		this.scoreFemme = scoreFemme;
		this.scoreOuvrier = scoreOuvrier;
		this.scoreCadre = scoreCadre;
		this.scoreFonctionPublique = scoreFonctionPublique;
		this.scoreSecteurPrive = scoreSecteurPrive;
		this.scoreCelibataire = scoreCelibataire;
		this.scoreMarie = scoreMarie;
		this.scoreLocataire = scoreLocataire;
		this.scorePropriétaire = scorePropriétaire;
		this.revenuSup = revenuSup;
		this.revenuInf = revenuInf;
		this.nombreEnfantInf = nombreEnfantInf;
		this.nombreEnfantSup = nombreEnfantSup;
		this.ageInf = ageInf;
		this.ageSup = ageSup;
		this.actifBooleanHomme = actifBooleanHomme;
		this.actifBooleanFemme = actifBooleanFemme;
		this.actifBooleanOuvrier = actifBooleanOuvrier;
		this.actifBooleanCadre = actifBooleanCadre;
		this.actifBooleanSecteurPrive = actifBooleanSecteurPrive;
		this.actifBooleanCelibataire = actifBooleanCelibataire;
		this.actifBooleanMarie = actifBooleanMarie;
		this.actifBooleanLocataire = actifBooleanLocataire;
		this.actifBooleanPropriétaire = actifBooleanPropriétaire;
		this.actifBooleanRevenuSup = actifBooleanRevenuSup;
		this.actifBooleanRevenuInf = actifBooleanRevenuInf;
		this.actifBooleanEnfantInf = actifBooleanEnfantInf;
		this.actifBooleanEnfantSup = actifBooleanEnfantSup;
		this.actifBooleanAgeInf = actifBooleanAgeInf;
		this.actifBooleanAgeSup = actifBooleanAgeSup;
	}

	@Id
	@Column(name = "identifiant", unique = true, nullable = false, length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "scoreHomme")
	public Integer getScoreHomme() {
		return this.scoreHomme;
	}

	public void setScoreHomme(Integer scoreHomme) {
		this.scoreHomme = scoreHomme;
	}

	@Column(name = "scoreFemme")
	public Integer getScoreFemme() {
		return this.scoreFemme;
	}

	public void setScoreFemme(Integer scoreFemme) {
		this.scoreFemme = scoreFemme;
	}

	@Column(name = "scoreOuvrier")
	public Integer getScoreOuvrier() {
		return this.scoreOuvrier;
	}

	public void setScoreOuvrier(Integer scoreOuvrier) {
		this.scoreOuvrier = scoreOuvrier;
	}

	@Column(name = "scoreCadre")
	public Integer getScoreCadre() {
		return this.scoreCadre;
	}

	public void setScoreCadre(Integer scoreCadre) {
		this.scoreCadre = scoreCadre;
	}

	@Column(name = "scoreFonctionPublique")
	public Integer getScoreFonctionPublique() {
		return this.scoreFonctionPublique;
	}

	public void setScoreFonctionPublique(Integer scoreFonctionPublique) {
		this.scoreFonctionPublique = scoreFonctionPublique;
	}

	@Column(name = "scoreSecteurPrive")
	public Integer getScoreSecteurPrive() {
		return this.scoreSecteurPrive;
	}

	public void setScoreSecteurPrive(Integer scoreSecteurPrive) {
		this.scoreSecteurPrive = scoreSecteurPrive;
	}

	@Column(name = "scoreCelibataire")
	public Integer getScoreCelibataire() {
		return this.scoreCelibataire;
	}

	public void setScoreCelibataire(Integer scoreCelibataire) {
		this.scoreCelibataire = scoreCelibataire;
	}

	@Column(name = "scoreMarie")
	public Integer getScoreMarie() {
		return this.scoreMarie;
	}

	public void setScoreMarie(Integer scoreMarie) {
		this.scoreMarie = scoreMarie;
	}

	@Column(name = "scoreLocataire")
	public Integer getScoreLocataire() {
		return this.scoreLocataire;
	}

	public void setScoreLocataire(Integer scoreLocataire) {
		this.scoreLocataire = scoreLocataire;
	}

	@Column(name = "scorePropriétaire")
	public Integer getScorePropriétaire() {
		return this.scorePropriétaire;
	}

	public void setScorePropriétaire(Integer scorePropriétaire) {
		this.scorePropriétaire = scorePropriétaire;
	}

	@Column(name = "revenuSup")
	public Integer getRevenuSup() {
		return this.revenuSup;
	}

	public void setRevenuSup(Integer revenuSup) {
		this.revenuSup = revenuSup;
	}

	@Column(name = "revenuInf")
	public Integer getRevenuInf() {
		return this.revenuInf;
	}

	public void setRevenuInf(Integer revenuInf) {
		this.revenuInf = revenuInf;
	}

	@Column(name = "nombreEnfantInf")
	public Integer getNombreEnfantInf() {
		return this.nombreEnfantInf;
	}

	public void setNombreEnfantInf(Integer nombreEnfantInf) {
		this.nombreEnfantInf = nombreEnfantInf;
	}

	@Column(name = "nombreEnfantSup")
	public Integer getNombreEnfantSup() {
		return this.nombreEnfantSup;
	}

	public void setNombreEnfantSup(Integer nombreEnfantSup) {
		this.nombreEnfantSup = nombreEnfantSup;
	}

	@Column(name = "ageInf")
	public Integer getAgeInf() {
		return this.ageInf;
	}

	public void setAgeInf(Integer ageInf) {
		this.ageInf = ageInf;
	}

	@Column(name = "ageSup")
	public Integer getAgeSup() {
		return this.ageSup;
	}

	public void setAgeSup(Integer ageSup) {
		this.ageSup = ageSup;
	}

	@Column(name = "actifBooleanHomme")
	public Boolean getActifBooleanHomme() {
		return this.actifBooleanHomme;
	}

	public void setActifBooleanHomme(Boolean actifBooleanHomme) {
		this.actifBooleanHomme = actifBooleanHomme;
	}

	@Column(name = "actifBooleanFemme")
	public Boolean getActifBooleanFemme() {
		return this.actifBooleanFemme;
	}

	public void setActifBooleanFemme(Boolean actifBooleanFemme) {
		this.actifBooleanFemme = actifBooleanFemme;
	}

	@Column(name = "actifBooleanOuvrier")
	public Boolean getActifBooleanOuvrier() {
		return this.actifBooleanOuvrier;
	}

	public void setActifBooleanOuvrier(Boolean actifBooleanOuvrier) {
		this.actifBooleanOuvrier = actifBooleanOuvrier;
	}

	@Column(name = "actifBooleanCadre")
	public Boolean getActifBooleanCadre() {
		return this.actifBooleanCadre;
	}

	public void setActifBooleanCadre(Boolean actifBooleanCadre) {
		this.actifBooleanCadre = actifBooleanCadre;
	}

	@Column(name = "actifBooleanSecteurPrive")
	public Boolean getActifBooleanSecteurPrive() {
		return this.actifBooleanSecteurPrive;
	}

	public void setActifBooleanSecteurPrive(Boolean actifBooleanSecteurPrive) {
		this.actifBooleanSecteurPrive = actifBooleanSecteurPrive;
	}

	@Column(name = "actifBooleanCelibataire")
	public Boolean getActifBooleanCelibataire() {
		return this.actifBooleanCelibataire;
	}

	public void setActifBooleanCelibataire(Boolean actifBooleanCelibataire) {
		this.actifBooleanCelibataire = actifBooleanCelibataire;
	}

	@Column(name = "actifBooleanMarie")
	public Boolean getActifBooleanMarie() {
		return this.actifBooleanMarie;
	}

	public void setActifBooleanMarie(Boolean actifBooleanMarie) {
		this.actifBooleanMarie = actifBooleanMarie;
	}

	@Column(name = "actifBooleanLocataire")
	public Boolean getActifBooleanLocataire() {
		return this.actifBooleanLocataire;
	}

	public void setActifBooleanLocataire(Boolean actifBooleanLocataire) {
		this.actifBooleanLocataire = actifBooleanLocataire;
	}

	@Column(name = "actifBooleanPropriétaire")
	public Boolean getActifBooleanPropriétaire() {
		return this.actifBooleanPropriétaire;
	}

	public void setActifBooleanPropriétaire(Boolean actifBooleanPropriétaire) {
		this.actifBooleanPropriétaire = actifBooleanPropriétaire;
	}

	@Column(name = "actifBooleanRevenuSup")
	public Boolean getActifBooleanRevenuSup() {
		return this.actifBooleanRevenuSup;
	}

	public void setActifBooleanRevenuSup(Boolean actifBooleanRevenuSup) {
		this.actifBooleanRevenuSup = actifBooleanRevenuSup;
	}

	@Column(name = "actifBooleanRevenuInf")
	public Boolean getActifBooleanRevenuInf() {
		return this.actifBooleanRevenuInf;
	}

	public void setActifBooleanRevenuInf(Boolean actifBooleanRevenuInf) {
		this.actifBooleanRevenuInf = actifBooleanRevenuInf;
	}

	@Column(name = "actifBooleanEnfantInf")
	public Boolean getActifBooleanEnfantInf() {
		return this.actifBooleanEnfantInf;
	}

	public void setActifBooleanEnfantInf(Boolean actifBooleanEnfantInf) {
		this.actifBooleanEnfantInf = actifBooleanEnfantInf;
	}

	@Column(name = "actifBooleanEnfantSup")
	public Boolean getActifBooleanEnfantSup() {
		return this.actifBooleanEnfantSup;
	}

	public void setActifBooleanEnfantSup(Boolean actifBooleanEnfantSup) {
		this.actifBooleanEnfantSup = actifBooleanEnfantSup;
	}

	@Column(name = "actifBooleanAgeInf")
	public Boolean getActifBooleanAgeInf() {
		return this.actifBooleanAgeInf;
	}

	public void setActifBooleanAgeInf(Boolean actifBooleanAgeInf) {
		this.actifBooleanAgeInf = actifBooleanAgeInf;
	}

	@Column(name = "actifBooleanAgeSup")
	public Boolean getActifBooleanAgeSup() {
		return this.actifBooleanAgeSup;
	}

	public void setActifBooleanAgeSup(Boolean actifBooleanAgeSup) {
		this.actifBooleanAgeSup = actifBooleanAgeSup;
	}

}
