package com.otv.model.mod;

// Generated 12 oct. 2014 00:06:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "ref")
public class Client implements java.io.Serializable {

	private Integer identifiant;
	private String civilite;
	private String nom;
	private String prenom;
	private Date dateNaissance;
	private String communeNaissance;
	private String adresseRue;
	private String adressecodePostal;
	private String adressePays;
	private String telephoneDomicile;
	private String telephonePortable;
	private String email;
	private String situationFamilial;
	private Integer nombreEnfant;
	private Date dateNaissancePremierEnfant;
	private Date dateNaissanceDeuxiemeEnfant;
	private String modeHabitation;
	private Integer nombrePersonneEnCharge;
	private String profession;
	private String anciennete;
	private String nomEmployeur;
	private String typeContrat;
	private String revenuPension;
	private String chargeLoyer;
	private String chargePremierPret;
	private String chargeDeuxiemePret;
	private Date date;

	public Client() {
	}

	public Client(String civilite, String nom, String prenom,
			Date dateNaissance, String communeNaissance, String adresseRue,
			String adressecodePostal, String adressePays,
			String telephoneDomicile, String telephonePortable, String email,
			String situationFamilial, Integer nombreEnfant,
			Date dateNaissancePremierEnfant, Date dateNaissanceDeuxiemeEnfant,
			String modeHabitation, Integer nombrePersonneEnCharge,
			String profession, String anciennete, String nomEmployeur,
			String typeContrat, String revenuPension, String chargeLoyer,
			String chargePremierPret, String chargeDeuxiemePret, Date date) {
		this.civilite = civilite;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.communeNaissance = communeNaissance;
		this.adresseRue = adresseRue;
		this.adressecodePostal = adressecodePostal;
		this.adressePays = adressePays;
		this.telephoneDomicile = telephoneDomicile;
		this.telephonePortable = telephonePortable;
		this.email = email;
		this.situationFamilial = situationFamilial;
		this.nombreEnfant = nombreEnfant;
		this.dateNaissancePremierEnfant = dateNaissancePremierEnfant;
		this.dateNaissanceDeuxiemeEnfant = dateNaissanceDeuxiemeEnfant;
		this.modeHabitation = modeHabitation;
		this.nombrePersonneEnCharge = nombrePersonneEnCharge;
		this.profession = profession;
		this.anciennete = anciennete;
		this.nomEmployeur = nomEmployeur;
		this.typeContrat = typeContrat;
		this.revenuPension = revenuPension;
		this.chargeLoyer = chargeLoyer;
		this.chargePremierPret = chargePremierPret;
		this.chargeDeuxiemePret = chargeDeuxiemePret;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "identifiant", unique = true, nullable = false)
	public Integer getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(Integer identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "civilite", length = 50)
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	@Column(name = "nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNaissance", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "communeNaissance", length = 50)
	public String getCommuneNaissance() {
		return this.communeNaissance;
	}

	public void setCommuneNaissance(String communeNaissance) {
		this.communeNaissance = communeNaissance;
	}

	@Column(name = "adresseRue", length = 50)
	public String getAdresseRue() {
		return this.adresseRue;
	}

	public void setAdresseRue(String adresseRue) {
		this.adresseRue = adresseRue;
	}

	@Column(name = "adressecodePostal", length = 50)
	public String getAdressecodePostal() {
		return this.adressecodePostal;
	}

	public void setAdressecodePostal(String adressecodePostal) {
		this.adressecodePostal = adressecodePostal;
	}

	@Column(name = "adressePays", length = 50)
	public String getAdressePays() {
		return this.adressePays;
	}

	public void setAdressePays(String adressePays) {
		this.adressePays = adressePays;
	}

	@Column(name = "telephoneDomicile", length = 50)
	public String getTelephoneDomicile() {
		return this.telephoneDomicile;
	}

	public void setTelephoneDomicile(String telephoneDomicile) {
		this.telephoneDomicile = telephoneDomicile;
	}

	@Column(name = "telephonePortable", length = 50)
	public String getTelephonePortable() {
		return this.telephonePortable;
	}

	public void setTelephonePortable(String telephonePortable) {
		this.telephonePortable = telephonePortable;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "situationFamilial", length = 50)
	public String getSituationFamilial() {
		return this.situationFamilial;
	}

	public void setSituationFamilial(String situationFamilial) {
		this.situationFamilial = situationFamilial;
	}

	@Column(name = "NombreEnfant")
	public Integer getNombreEnfant() {
		return this.nombreEnfant;
	}

	public void setNombreEnfant(Integer nombreEnfant) {
		this.nombreEnfant = nombreEnfant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNaissancePremierEnfant", length = 10)
	public Date getDateNaissancePremierEnfant() {
		return this.dateNaissancePremierEnfant;
	}

	public void setDateNaissancePremierEnfant(Date dateNaissancePremierEnfant) {
		this.dateNaissancePremierEnfant = dateNaissancePremierEnfant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNaissanceDeuxiemeEnfant", length = 10)
	public Date getDateNaissanceDeuxiemeEnfant() {
		return this.dateNaissanceDeuxiemeEnfant;
	}

	public void setDateNaissanceDeuxiemeEnfant(Date dateNaissanceDeuxiemeEnfant) {
		this.dateNaissanceDeuxiemeEnfant = dateNaissanceDeuxiemeEnfant;
	}

	@Column(name = "modeHabitation", length = 50)
	public String getModeHabitation() {
		return this.modeHabitation;
	}

	public void setModeHabitation(String modeHabitation) {
		this.modeHabitation = modeHabitation;
	}

	@Column(name = "NombrePersonneEnCharge")
	public Integer getNombrePersonneEnCharge() {
		return this.nombrePersonneEnCharge;
	}

	public void setNombrePersonneEnCharge(Integer nombrePersonneEnCharge) {
		this.nombrePersonneEnCharge = nombrePersonneEnCharge;
	}

	@Column(name = "Profession", length = 50)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "anciennete", length = 50)
	public String getAnciennete() {
		return this.anciennete;
	}

	public void setAnciennete(String anciennete) {
		this.anciennete = anciennete;
	}

	@Column(name = "nomEmployeur", length = 50)
	public String getNomEmployeur() {
		return this.nomEmployeur;
	}

	public void setNomEmployeur(String nomEmployeur) {
		this.nomEmployeur = nomEmployeur;
	}

	@Column(name = "typeContrat", length = 50)
	public String getTypeContrat() {
		return this.typeContrat;
	}

	public void setTypeContrat(String typeContrat) {
		this.typeContrat = typeContrat;
	}

	@Column(name = "RevenuPension", length = 50)
	public String getRevenuPension() {
		return this.revenuPension;
	}

	public void setRevenuPension(String revenuPension) {
		this.revenuPension = revenuPension;
	}

	@Column(name = "ChargeLoyer", length = 50)
	public String getChargeLoyer() {
		return this.chargeLoyer;
	}

	public void setChargeLoyer(String chargeLoyer) {
		this.chargeLoyer = chargeLoyer;
	}

	@Column(name = "ChargePremierPret", length = 50)
	public String getChargePremierPret() {
		return this.chargePremierPret;
	}

	public void setChargePremierPret(String chargePremierPret) {
		this.chargePremierPret = chargePremierPret;
	}

	@Column(name = "ChargeDeuxiemePret", length = 50)
	public String getChargeDeuxiemePret() {
		return this.chargeDeuxiemePret;
	}

	public void setChargeDeuxiemePret(String chargeDeuxiemePret) {
		this.chargeDeuxiemePret = chargeDeuxiemePret;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
