package com.otv.model.mod;

// Generated 12 oct. 2014 00:06:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historique generated by hbm2java
 */
@Entity
@Table(name = "historique", catalog = "ref")
public class Historique implements java.io.Serializable {

	private Integer identifiant;
	private String idCredit;
	private String nom;
	private String prenom;
	private String montant;
	private String mensualite;
	private String statut;
	private Date date;
	private String validePar;
	private String envoyerPar;
	private String envoyerVers;
	private String commentaire;

	public Historique() {
	}

	public Historique(String idCredit, String nom, String prenom,
			String montant, String mensualite, String statut, Date date,
			String validePar, String envoyerPar, String envoyerVers,
			String commentaire) {
		this.idCredit = idCredit;
		this.nom = nom;
		this.prenom = prenom;
		this.montant = montant;
		this.mensualite = mensualite;
		this.statut = statut;
		this.date = date;
		this.validePar = validePar;
		this.envoyerPar = envoyerPar;
		this.envoyerVers = envoyerVers;
		this.commentaire = commentaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "identifiant", unique = true, nullable = false)
	public Integer getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(Integer identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "idCredit", length = 50)
	public String getIdCredit() {
		return this.idCredit;
	}

	public void setIdCredit(String idCredit) {
		this.idCredit = idCredit;
	}

	@Column(name = "Nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Montant", length = 50)
	public String getMontant() {
		return this.montant;
	}

	public void setMontant(String montant) {
		this.montant = montant;
	}

	@Column(name = "Mensualite", length = 50)
	public String getMensualite() {
		return this.mensualite;
	}

	public void setMensualite(String mensualite) {
		this.mensualite = mensualite;
	}

	@Column(name = "Statut", length = 50)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "validePar", length = 50)
	public String getValidePar() {
		return this.validePar;
	}

	public void setValidePar(String validePar) {
		this.validePar = validePar;
	}

	@Column(name = "envoyerPar", length = 50)
	public String getEnvoyerPar() {
		return this.envoyerPar;
	}

	public void setEnvoyerPar(String envoyerPar) {
		this.envoyerPar = envoyerPar;
	}

	@Column(name = "envoyerVers", length = 50)
	public String getEnvoyerVers() {
		return this.envoyerVers;
	}

	public void setEnvoyerVers(String envoyerVers) {
		this.envoyerVers = envoyerVers;
	}

	@Column(name = "commentaire", length = 50)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

}
