package com.otv.model.mod;

// Generated 12 oct. 2014 00:06:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "ref")
public class Patient implements java.io.Serializable {

	private Integer identifant;
	private String nom;
	private String prenom;
	private String telephone;
	private String statut;
	private Date dateMiseAjour;

	public Patient() {
	}

	public Patient(String nom) {
		this.nom = nom;
	}

	public Patient(String nom, String prenom, String telephone, String statut,
			Date dateMiseAjour) {
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.statut = statut;
		this.dateMiseAjour = dateMiseAjour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "identifant", unique = true, nullable = false)
	public Integer getIdentifant() {
		return this.identifant;
	}

	public void setIdentifant(Integer identifant) {
		this.identifant = identifant;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 250)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "telephone", length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "statut", length = 50)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateMiseAjour", length = 10)
	public Date getDateMiseAjour() {
		return this.dateMiseAjour;
	}

	public void setDateMiseAjour(Date dateMiseAjour) {
		this.dateMiseAjour = dateMiseAjour;
	}

}
