package com.otv.model.mod;

// Generated 12 oct. 2014 00:06:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Scoring generated by hbm2java
 */
@Entity
@Table(name = "scoring", catalog = "ref")
public class Scoring implements java.io.Serializable {

	private String identifiant;
	private String age;
	private String genre;
	private String regimeMatrimonial;
	private Integer nombreEnfant;
	private Integer nombrePersonneEnCharge;
	private String profession;
	private Long revenu;
	private Long modeHabitation;
	private Date date;

	public Scoring() {
	}

	public Scoring(String identifiant) {
		this.identifiant = identifiant;
	}

	public Scoring(String identifiant, String age, String genre,
			String regimeMatrimonial, Integer nombreEnfant,
			Integer nombrePersonneEnCharge, String profession, Long revenu,
			Long modeHabitation, Date date) {
		this.identifiant = identifiant;
		this.age = age;
		this.genre = genre;
		this.regimeMatrimonial = regimeMatrimonial;
		this.nombreEnfant = nombreEnfant;
		this.nombrePersonneEnCharge = nombrePersonneEnCharge;
		this.profession = profession;
		this.revenu = revenu;
		this.modeHabitation = modeHabitation;
		this.date = date;
	}

	@Id
	@Column(name = "identifiant", unique = true, nullable = false, length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "age", length = 50)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "genre", length = 50)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "regimeMatrimonial", length = 50)
	public String getRegimeMatrimonial() {
		return this.regimeMatrimonial;
	}

	public void setRegimeMatrimonial(String regimeMatrimonial) {
		this.regimeMatrimonial = regimeMatrimonial;
	}

	@Column(name = "NombreEnfant")
	public Integer getNombreEnfant() {
		return this.nombreEnfant;
	}

	public void setNombreEnfant(Integer nombreEnfant) {
		this.nombreEnfant = nombreEnfant;
	}

	@Column(name = "NombrePersonneEnCharge")
	public Integer getNombrePersonneEnCharge() {
		return this.nombrePersonneEnCharge;
	}

	public void setNombrePersonneEnCharge(Integer nombrePersonneEnCharge) {
		this.nombrePersonneEnCharge = nombrePersonneEnCharge;
	}

	@Column(name = "Profession", length = 50)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "Revenu", precision = 10, scale = 0)
	public Long getRevenu() {
		return this.revenu;
	}

	public void setRevenu(Long revenu) {
		this.revenu = revenu;
	}

	@Column(name = "ModeHabitation", precision = 10, scale = 0)
	public Long getModeHabitation() {
		return this.modeHabitation;
	}

	public void setModeHabitation(Long modeHabitation) {
		this.modeHabitation = modeHabitation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
