package com.recouvrement.model;

// Generated 30 nov. 2014 01:21:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actionclient generated by hbm2java
 */
@Entity
@Table(name = "actionclient", catalog = "ref")
public class Actionclient implements java.io.Serializable {

	private Integer identifiant;
	private Integer nbreDossier;
	private String typeaction;
	private Date dateAction;

	public Actionclient() {
	}

	public Actionclient(Integer nbreDossier, String typeaction, Date dateAction) {
		this.nbreDossier = nbreDossier;
		this.typeaction = typeaction;
		this.dateAction = dateAction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "identifiant", unique = true, nullable = false)
	public Integer getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(Integer identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "nbreDossier")
	public Integer getNbreDossier() {
		return this.nbreDossier;
	}

	public void setNbreDossier(Integer nbreDossier) {
		this.nbreDossier = nbreDossier;
	}

	@Column(name = "typeaction", length = 50)
	public String getTypeaction() {
		return this.typeaction;
	}

	public void setTypeaction(String typeaction) {
		this.typeaction = typeaction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateAction", length = 10)
	public Date getDateAction() {
		return this.dateAction;
	}

	public void setDateAction(Date dateAction) {
		this.dateAction = dateAction;
	}

}
