package com.recouvrement.model;

// Generated 12 sept. 2014 23:37:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Articles generated by hbm2java
 */
@Entity
@Table(name = "articles", catalog = "ref")
public class Articles implements java.io.Serializable {

	private Integer ideArt;
	private String nomArt;
	private String desArt;
	private String tailArt;
	private float priArt;
	private String imgArt;

	public Articles() {
	}

	public Articles(String nomArt, String desArt, String tailArt, float priArt,
			String imgArt) {
		this.nomArt = nomArt;
		this.desArt = desArt;
		this.tailArt = tailArt;
		this.priArt = priArt;
		this.imgArt = imgArt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ide_art", unique = true, nullable = false)
	public Integer getIdeArt() {
		return this.ideArt;
	}

	public void setIdeArt(Integer ideArt) {
		this.ideArt = ideArt;
	}

	@Column(name = "nom_art", nullable = false, length = 30)
	public String getNomArt() {
		return this.nomArt;
	}

	public void setNomArt(String nomArt) {
		this.nomArt = nomArt;
	}

	@Column(name = "des_art", nullable = false, length = 80)
	public String getDesArt() {
		return this.desArt;
	}

	public void setDesArt(String desArt) {
		this.desArt = desArt;
	}

	@Column(name = "tail_art", nullable = false, length = 10)
	public String getTailArt() {
		return this.tailArt;
	}

	public void setTailArt(String tailArt) {
		this.tailArt = tailArt;
	}

	@Column(name = "pri_art", nullable = false, precision = 12, scale = 0)
	public float getPriArt() {
		return this.priArt;
	}

	public void setPriArt(float priArt) {
		this.priArt = priArt;
	}

	@Column(name = "img_art", nullable = false, length = 15)
	public String getImgArt() {
		return this.imgArt;
	}

	public void setImgArt(String imgArt) {
		this.imgArt = imgArt;
	}

}
