package com.recouvrement.model;

// Generated 30 nov. 2014 01:21:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historiqueappelentrant generated by hbm2java
 */
@Entity
@Table(name = "historiqueappelentrant", catalog = "ref")
public class Historiqueappelentrant implements java.io.Serializable {

	private Integer idAppel;
	private Date dateAppel;
	private String idClient;
	private String idDossier;

	public Historiqueappelentrant() {
	}

	public Historiqueappelentrant(Date dateAppel, String idClient,
			String idDossier) {
		this.dateAppel = dateAppel;
		this.idClient = idClient;
		this.idDossier = idDossier;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAppel", unique = true, nullable = false)
	public Integer getIdAppel() {
		return this.idAppel;
	}

	public void setIdAppel(Integer idAppel) {
		this.idAppel = idAppel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateAppel", length = 10)
	public Date getDateAppel() {
		return this.dateAppel;
	}

	public void setDateAppel(Date dateAppel) {
		this.dateAppel = dateAppel;
	}

	@Column(name = "idClient", length = 50)
	public String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(String idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idDossier", length = 50)
	public String getIdDossier() {
		return this.idDossier;
	}

	public void setIdDossier(String idDossier) {
		this.idDossier = idDossier;
	}

}
