package com.recouvrement.model;

// Generated 30 nov. 2014 01:21:08 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historiquedossierconfie generated by hbm2java
 */
@Entity
@Table(name = "historiquedossierconfie", catalog = "ref")
public class Historiquedossierconfie implements java.io.Serializable {

	private Integer idDossierConfie;
	private Date dateDossierConfie;
	private String idClient;
	private String idDossier;

	public Historiquedossierconfie() {
	}

	public Historiquedossierconfie(Date dateDossierConfie, String idClient,
			String idDossier) {
		this.dateDossierConfie = dateDossierConfie;
		this.idClient = idClient;
		this.idDossier = idDossier;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDossierConfie", unique = true, nullable = false)
	public Integer getIdDossierConfie() {
		return this.idDossierConfie;
	}

	public void setIdDossierConfie(Integer idDossierConfie) {
		this.idDossierConfie = idDossierConfie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDossierConfie", length = 10)
	public Date getDateDossierConfie() {
		return this.dateDossierConfie;
	}

	public void setDateDossierConfie(Date dateDossierConfie) {
		this.dateDossierConfie = dateDossierConfie;
	}

	@Column(name = "idClient", length = 50)
	public String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(String idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idDossier", length = 50)
	public String getIdDossier() {
		return this.idDossier;
	}

	public void setIdDossier(String idDossier) {
		this.idDossier = idDossier;
	}

}
