package com.recouvrement.model;

// Generated 30 nov. 2014 01:21:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promesse generated by hbm2java
 */
@Entity
@Table(name = "promesse", catalog = "ref")
public class Promesse implements java.io.Serializable {

	private Integer idPromesse;
	private String statutPromesse;
	private String commentaire;
	private Date datePromesse;
	private Date nouvelleDatePromesse;
	private String idClient;
	private String idDossier;
	private Date dateEnregistrement;
	private Integer montantPromesse;

	
	
	public Promesse() {
	}

	public Promesse(Date dateEnregistrement) {
		this.dateEnregistrement = dateEnregistrement;
	}

	public Promesse(String statutPromesse, Date datePromesse,
			Date nouvelleDatePromesse, String idClient, String idDossier,
			Date dateEnregistrement, Integer montantPromesse) {
		this.statutPromesse = statutPromesse;
		this.datePromesse = datePromesse;
		this.nouvelleDatePromesse = nouvelleDatePromesse;
		this.idClient = idClient;
		this.idDossier = idDossier;
		this.dateEnregistrement = dateEnregistrement;
		this.montantPromesse = montantPromesse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPromesse", unique = true, nullable = false)
	public Integer getIdPromesse() {
		return this.idPromesse;
	}

	public void setIdPromesse(Integer idPromesse) {
		this.idPromesse = idPromesse;
	}

	@Column(name = "statutPromesse", length = 50)
	public String getStatutPromesse() {
		return this.statutPromesse;
	}

	
	@Column(name = "commentaire", length = 200)
	public String getCommentaire() {
		return this.commentaire;
	}
	
	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public void setStatutPromesse(String statutPromesse) {
		this.statutPromesse = statutPromesse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datePromesse", length = 10)
	public Date getDatePromesse() {
		return this.datePromesse;
	}

	public void setDatePromesse(Date datePromesse) {
		this.datePromesse = datePromesse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nouvelleDatePromesse", length = 10)
	public Date getNouvelleDatePromesse() {
		return this.nouvelleDatePromesse;
	}

	public void setNouvelleDatePromesse(Date nouvelleDatePromesse) {
		this.nouvelleDatePromesse = nouvelleDatePromesse;
	}

	@Column(name = "idClient", length = 50)
	public String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(String idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idDossier", length = 50)
	public String getIdDossier() {
		return this.idDossier;
	}

	public void setIdDossier(String idDossier) {
		this.idDossier = idDossier;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dateEnregistrement", nullable = false, length = 10)
	public Date getDateEnregistrement() {
		return this.dateEnregistrement;
	}

	public void setDateEnregistrement(Date dateEnregistrement) {
		this.dateEnregistrement = dateEnregistrement;
	}
	
	
	@Column(name = "montantPromesse")
	public Integer getMontantPromesse() {
		return this.montantPromesse;
	}

	public void setMontantPromesse(Integer montantPromesse) {
		this.montantPromesse = montantPromesse;
	}

}
