package com.recouvrement.model;

// Generated 12 sept. 2014 23:37:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Revenuordepense generated by hbm2java
 */
@Entity
@Table(name = "revenuordepense", catalog = "ref")
public class Revenuordepense implements java.io.Serializable {

	private String libelle;
	private Long montant;
	private String type;
	private Date date;

	public Revenuordepense() {
	}

	public Revenuordepense(String libelle) {
		this.libelle = libelle;
	}

	public Revenuordepense(String libelle, Long montant, String type, Date date) {
		this.libelle = libelle;
		this.montant = montant;
		this.type = type;
		this.date = date;
	}

	@Id
	@Column(name = "libelle", unique = true, nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "montant", precision = 10, scale = 0)
	public Long getMontant() {
		return this.montant;
	}

	public void setMontant(Long montant) {
		this.montant = montant;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
